# Start from the latest golang base image
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o transaction-service ./cmd/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/transaction-service .
EXPOSE 8081
CMD ["./transaction-service"] 